/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Model.Koneksi;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alvin
 */
public class FormSupplier extends javax.swing.JFrame {
    
    // attribute untuk menyimpan id/PK saat mengedit dan menghapus
    private String id_supplier;

    /**
     * Creates new form FormSupplier
     */
    //  menampilkan form awal saat kode dieksekusi
    public FormSupplier() {
        initComponents();
        load_table();
    }
    
    // memunculkan tabel ke dalam interface JTable
    private void load_table() {
        // membuat object baru     
        DefaultTableModel model = new DefaultTableModel();
        //  membuat column untuk field tabel
        model.addColumn("No. Supplier");
        model.addColumn("Nama");        
        model.addColumn("Email");
        model.addColumn("Alamat");
        model.addColumn("No HP");

        try {
            String sql = "SELECT * from tb_supplier";// variable berisi query SQL
            java.sql.Connection conn = (Connection) Koneksi.koneksiDB(); // membuat koneksi baru ke database
            java.sql.Statement stm = conn.createStatement(); // membuat SQL server statement untuk dikirm ke database
            java.sql.ResultSet res = stm.executeQuery(sql); // mengeksekusi statement SQL
            //  membuat looping untuk menampilkan semua baris data
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getInt(1), 
                    res.getString(2), 
                    res.getString(3),
                    res.getString(4),                    
                    res.getString(5),
                });
            }
            //  menampilkan data di console untuk debuging
            System.out.println("Data: " + res);
            //  mengisi Jtabel
            TbSupplier.setModel(model);
        } catch (Exception e) {
            // menampilkan eror di console
            System.out.println("Error Found: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Email = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbSupplier = new javax.swing.JTable();
        NoHp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Edit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        NamaSupplier = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Alamat = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        Save.setText("SAVE");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Clear.setText("CLEAR");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        TbSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TbSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbSupplierMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TbSupplier);

        NoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoHpActionPerformed(evt);
            }
        });

        jLabel9.setText("No HP");

        Edit.setText("EDIT");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        jLabel2.setText("Alamat");

        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        NamaSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaSupplierActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Supplier");

        jLabel5.setText("Email");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUPPLIER");

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(322, 322, 322)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Save)
                        .addGap(18, 18, 18)
                        .addComponent(Edit)
                        .addGap(18, 18, 18)
                        .addComponent(Clear)
                        .addGap(18, 18, 18)
                        .addComponent(Delete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Alamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(NamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(NamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(Edit)
                    .addComponent(Clear)
                    .addComponent(Delete))
                .addGap(143, 143, 143))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void NoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoHpActionPerformed

    // mengupdate data
    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        try {
            // membuat koneksi baru
            Koneksi ObjKoneksi = new Koneksi();
            Connection con = ObjKoneksi.koneksiDB();
            Statement st = con.createStatement();
             // Membuat query dan langsung mengisinya saat dipanggil
            String sql = "update tb_supplier set nama='"+ NamaSupplier.getText() + "', email ='" + Email.getText() + "',"+ "alamat ='" + Alamat.getText() + "',no_hp = " + NoHp.getText() + " where id_supplier = " + id_supplier;
            int row = st.executeUpdate(sql);//eksekusi query sql
            if (row == 1) {
                // menampilkan UI pop up berhasil
                JOptionPane.showMessageDialog(null, "Sukses merubah data", "Data Supplier", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            // menampilkan UI pop up gagal
            JOptionPane.showMessageDialog(null, e, "Data Supplier", JOptionPane.ERROR_MESSAGE);
        }
        //  menampilkan table
        load_table();
    }//GEN-LAST:event_EditActionPerformed

    // menghapus data yang dipilih
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        try {
            // membuat koneksi baru
            Koneksi ObjKoneksi = new Koneksi();
            Connection con = ObjKoneksi.koneksiDB();
            Statement st = con.createStatement();
            // Membuat query dan langsung mengisinya saat dipanggil
            String sql = "delete from tb_supplier where id_supplier = " + id_supplier;
            int row = st.executeUpdate(sql);//eksekusi query sql
            if (row == 1) {
                // menampilkan UI pop up berhasil
                JOptionPane.showMessageDialog(null, "Data sukses dihapus", "Data Supplier", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            // menampilkan UI pop up gagal
            JOptionPane.showMessageDialog(null, "Data gagal dihapus", "Data Supplier", JOptionPane.ERROR_MESSAGE);
        }
        //  menampilkan table
        load_table();
    }//GEN-LAST:event_DeleteActionPerformed

    private void NamaSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaSupplierActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // membuat objek
        FormMaster fmkembali = new FormMaster();
        // menampilkan menu utama
        fmkembali.show();
        // membersihkan data yang disimpan didalam object global
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // menambahkan data
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        try {
            // membuat koneksi baru
            Koneksi ObjKoneksi = new Koneksi();
            Connection con = ObjKoneksi.koneksiDB();
            Statement st = con.createStatement();
            // Membuat query dan langsung mengisinya saat dipanggil
            String sql = "insert into tb_supplier(nama,email,alamat,no_hp) "
                    + "values ('" + NamaSupplier.getText() + "', '" + Email.getText() + "', '" + Alamat.getText()+ "', '" + NoHp.getText() + "')";
            int row = st.executeUpdate(sql);//eksekusi query sql
            if (row == 1) {
                // menampilkan UI pop up berhasil
                JOptionPane.showMessageDialog(null, "Sukses menambahkan supplier", "Data Supplier", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (SQLException e) {
            // menampilkan UI pop up gagal
            JOptionPane.showMessageDialog(null, e, "Data Supplier", JOptionPane.INFORMATION_MESSAGE);
            // menampilkan eror di console
            System.out.println("gagal menambah kedalam database \n" + e);
        }
        //  menampilkan table
        load_table();
    }//GEN-LAST:event_SaveActionPerformed

    // memilih data
    private void TbSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbSupplierMouseClicked
        // TODO add your handling code here:
        // mengisi JTextField dengan data yang telah dipilih pada di Jtable
        id_supplier = TbSupplier.getValueAt(TbSupplier.getSelectedRow(), 0).toString();
        NamaSupplier.setText(TbSupplier.getValueAt(TbSupplier.getSelectedRow(), 1).toString());
        Email.setText(TbSupplier.getValueAt(TbSupplier.getSelectedRow(), 2).toString());
        Alamat.setText(TbSupplier.getValueAt(TbSupplier.getSelectedRow(), 3).toString());
        NoHp.setText(TbSupplier.getValueAt(TbSupplier.getSelectedRow(), 4).toString());
        
        // melihat status pengeditan pada JTable
        boolean editTbl = TbSupplier.isEditing();
        // jika pemilihan data berhasil
        if (editTbl == false) {
            // menampilkan UI pop up berhasil
            JOptionPane.showMessageDialog(null, "Sukses memilih Data Supplier", "Data Sepatu", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TbSupplierMouseClicked

    // mengosongkan semua JTextField
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        // mengatur semua jenis JTextField menjadi null
        NamaSupplier.setText("");
        Email.setText("");
        Alamat.setText("");
        NoHp.setText("");
    }//GEN-LAST:event_ClearActionPerformed
                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea Alamat;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField NamaSupplier;
    private javax.swing.JTextField NoHp;
    private javax.swing.JButton Save;
    private javax.swing.JTable TbSupplier;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
